In [1]:
import numpy as np

1 - Definition of Matrix Multiplication

If 𝐴
is an 𝑚×𝑛 matrix and 𝐵 is an 𝑛×𝑝 matrix, the matrix product 𝐶=𝐴𝐵 (denoted without multiplication signs or dots) is defined to be the 𝑚×𝑝 matrix such that 𝑐𝑖𝑗=𝑎𝑖1𝑏1𝑗+𝑎𝑖2𝑏2𝑗+…+𝑎𝑖𝑛𝑏𝑛𝑗=∑𝑛𝑘=1𝑎𝑖𝑘𝑏𝑘𝑗,(4)

where 𝑎𝑖𝑘
are the elements of matrix 𝐴, 𝑏𝑘𝑗 are the elements of matrix 𝐵, and 𝑖=1,…,𝑚, 𝑘=1,…,𝑛, 𝑗=1,…,𝑝. In other words, 𝑐𝑖𝑗 is the dot product of the 𝑖-th row of 𝐴 and the 𝑗-th column of 𝐵

.

2 - Matrix Multiplication using Python

Like with the dot product, there are a few ways to perform matrix multiplication in Python. As discussed in the previous lab, the calculations are more efficient in the vectorized form. Let's discuss the most commonly used functions in the vectorized form. First, define two matrices:


In [2]:
A = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
print("Matrix A (3 by 3):\n", A)

B = np.array([[2, 2], [5, 7], [4, 4]])
print("Matrix B (3 by 2):\n", B)

Matrix A (3 by 3):
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix B (3 by 2):
 [[2 2]
 [5 7]
 [4 4]]


In [3]:
np.matmul(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [5]:
#Which will output 3×2 matrix as a np.array. Python operator @ will also work here giving the same result:
A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

3 - Matrix Convention and Broadcasting

Mathematically, matrix multiplication is defined only if number of the columns of matrix 𝐴
is equal to the number of the rows of matrix 𝐵

(you can check again the definition in the secition 1 and see that otherwise the dot products between rows and columns will not be defined).

Thus, in the example above (2), changing the order of matrices when performing the multiplication 𝐵𝐴
will not work as the above rule does not hold anymore. You can check it by running the cells below - both of them will give errors.

In [6]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])

print("Shape of vector x:", x.shape)
print("Number of dimensions of vector x:", x.ndim)
print("Shape of vector x, reshaped to a matrix:", x.reshape((3, 1)).shape)
print("Number of dimensions of vector x, reshaped to a matrix:", x.reshape((3, 1)).ndim)

Shape of vector x: (3,)
Number of dimensions of vector x: 1
Shape of vector x, reshaped to a matrix: (3, 1)
Number of dimensions of vector x, reshaped to a matrix: 2


In [7]:
np.matmul(x,y)

3

In [8]:
try:
    np.matmul(x.reshape((3, 1)), y.reshape((3, 1)))
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)


In [9]:
np.dot(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [10]:
A - 2

array([[ 2,  7,  7],
       [ 7, -1,  4],
       [ 7,  0,  1]])