In [1]:
import numpy as np

In [2]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


In [3]:
# Create and print a NumPy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [5]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


What if you wanted to create an array with five evenly spaced values in the interval from 0 to 100? As you may notice, you have 3 parameters that a function must take. One paremeter is the starting number, in this case 0, the final number 100 and the number of elements in the array, in this case, 5. NumPy has a function that allows you to do specifically this by using np.linspace().


In [6]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [7]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)
c_int = np.arange(1, 20, 3, dtype=int)
print(c_int)
b_float = np.arange(3, dtype=float)
print(b_float)
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype) # Prints the data type of the array

[  0  25  50  75 100]
[ 1  4  7 10 13 16 19]
[0. 1. 2.]
['Welcome to Math for ML!']
<U23


<a name='1-4'></a>
## 1.4 - More on NumPy arrays ##

One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as: 
- `np.ones()` - Returns a new array setting values to one.
- `np.zeros()` - Returns a new array setting values to zero.
- `np.empty()` - Returns a new uninitialized array. 
- `np.random.rand()` - Returns a new array with values chosen at random.

In [8]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [9]:
# 1-D array 
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, # the array to be reshaped
               (2,3) # dimensions of the new array
              )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


In [10]:
# Dimension of the 2-D array multi_dim_arr
multi_dim_arr.ndim

2

In [11]:
# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
multi_dim_arr.shape

(2, 3)

In [12]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_arr.size

6